export {default as Navbar} from './Navbar'
export {default as HomePage} from './Navbar'
export {default as Cryptocurrencies} from './Navbar'
export {default as CryptoDetails} from './Navbar'
export {default as News} from './Navbar'
export {default as Exchanges} from './Navbar'